"""add indexes

Revision ID: 2a77d78d1a9f
Revises: d0ce8871b733
Create Date: 2021-12-20 17:01:40.319568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a77d78d1a9f'
down_revision = 'd0ce8871b733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_money_transfers_date_modified'), 'money_transfers', ['date_modified'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_money_transfers_date_modified'), table_name='money_transfers')
    # ### end Alembic commands ###
